apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          volumeMounts:
            - name: var-log
              mountPath: /var/log
            - name: docker-log
              mountPath: /var/lib/docker/containers
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: promtail-config
              mountPath: /etc/promtail/config.yaml
              subPath: promtail-config.yaml
          command: ["/usr/bin/promtail", "-config.file=/etc/promtail/config.yaml"]
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: docker-log
          hostPath:
            path: /var/lib/docker/containers
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: promtail-config
          configMap:
            name: promtail-config

---
