apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappredis
  labels:
    app: myappredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappredis
  template:
    metadata:
      labels:
        app: myappredis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: myappredis
spec:
  type: LoadBalancer
  selector:
    app: myappredis
  ports:
    - port: 6379
      targetPort: 6379
