apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"prometheus","namespace":"monitoring"},"spec":{"ports":[{"port":9090,"targetPort":9090}],"selector":{"app":"prometheus"}}}
  creationTimestamp: "2024-05-13T17:57:22Z"
  name: prometheus
  namespace: monitoring
  resourceVersion: "71313"
  uid: 9268e0b0-6d26-43d3-bbbd-f9b66cb719d7
spec:
  clusterIP: 10.96.64.29
  clusterIPs:
    - 10.96.64.29
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
