apiVersion: v1
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: flog_scrape
        docker_sd_configs:
          - host: unix:///var/run/docker.sock
          refresh_interval: 5s
        relabel_configs:
          - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'application'

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"promtail-config.yaml":"server:\n  http_listen_port: 9080\n  grpc_listen_port: 0\n\npositions:\n  filename: /tmp/positions.yaml\n\nclients:\n  - url: http://loki:3100/loki/api/v1/push\n\nscrape_configs:\n  - job_name: kubernetes-containers\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      - source_labels: ['__meta_kubernetes_pod_container_name']\n        regex: '(.+)'\n        target_label: 'container'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-05-13T11:11:05Z","name":"promtail-config","namespace":"monitoring","resourceVersion":"63694","uid":"b785a04b-1cff-4a42-a00b-88f054191f33"}}
  creationTimestamp: "2024-05-13T11:11:05Z"
  name: promtail-config
  namespace: monitoring
  resourceVersion: "66327"
  uid: b785a04b-1cff-4a42-a00b-88f054191f33
